[package]
name = "ANPR_Test"
version = "0.2.0"
edition = "2024"

[dependencies]
libc = "0.2"
ANPR_bind = {path = "../ANPR_bind"}

[profile.dev]
opt-level = 1 # Optimize for faster builds during development

[profile.release]
opt-level = 3 # Optimize for maximum performance